### PR TITLE
Mystery  of the lost footer

### PR DESCRIPTION
**Pull request by bdc-ehealth**

### CODE REVIEW

**Comment by costateixeira** [comment]
@bdc-ehealth does eHealth want to deliberately remove the link to the version history and the license icon? I think those are important to keep and from lookinga this PR, they will still not be displayed.

**Comment by costateixeira** [comment]
links version history and license icon look like this - not an issue if we lose them (we had them at some point) but I just want to confirm: 
image

**Comment by bdc-ehealth** [comment]
@costateixeira I put back the contents of a version of the footer you yourself provided: https://github.com/hl7-be/hl7.be.fhir.template/commit/d4c118649063532f09157a799becf61d644df41f . There is no other dark reason that can be found. I give you the full liberty to change whatever you want, as long as you abide by the decision of the HL7 Belgium FHIR Validation team that introduces the 3 colours to make the visual distinction between Draft IGs , eHealth Platform Approved IGs (Belgian National Standard) and HL7 Belgium standards.

**Comment by costateixeira** [comment]
Not sure if "I put" is present or past. Do you plan to do more changes here, or can I fix it?

**Comment by costateixeira** [comment]
This last change now fixes the footer for the other folders. 
@bdc-ehealth My small question was whether eHealth wants to remove the link to version history and license from eHealth - which are missing per the changes you made, so I assume it is intentional and will merge as is - if you want to add back those links, it's easy.
image

**Comment by costateixeira** [comment]
Tested on base and depending IGs. Seems to be OK now.

**Pull request merged**
